### PR TITLE
Add CODEOWNERS and Fix deletion mapping leaking

### PR DESCRIPTION
**Pull request by sorpaas**
Ping also @jacogr

### CODE REVIEW

**Comment by sorpaas** [comment]
I'm going to try to get done 100% coverage for this.

**Comment by andresilva** [comment]
@sorpaas I think @twittner is currently writing a test spec for this contract (created from this branch). Maybe it's better to sync up with him?

**Comment by sorpaas** [comment]
Ah okay. @twittner let me know if there's anything I can help!

**Comment by twittner** [comment]
Thanks @sorpaas, I haven't completed the tests yet. Work in progress is here: https://github.com/twittner/token-registry/tree/tests

**Pull request merged**
